import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
    badgeLabelForEvidenceType,
    getVisualEnrichment,
    isPlaceholderSourceLabel,
    normalizeBlogDiagramGraph,
    normalizeEvidenceForVisualBlock,
    sanitizeEvidenceSourceLabel,
    sourceNoteForEvidenceType,
    type BlogVisualBlock,
} from "./visual-enrichment";

const legacyAiResearchSynthesisLabel = `AI ${"research"} synthesis`;
const legacyAiSynthesisLabel = `AI ${"synthesis"}`;

const chartBlock: BlogVisualBlock = {
    id: "chart_adoption",
    type: "chart",
    title: "AI adoption benchmark",
    description: "Shows adoption movement.",
    caption: "Adoption rose in the cited sample.",
    source_label: legacyAiResearchSynthesisLabel,
    source_url: "https://www.mckinsey.com/capabilities/quantum-research/example",
    seo_alt: "AI adoption benchmark chart",
    chart_type: "bar",
    unit: "%",
    data: [{ label: "Adoption", value: 72 }],
};

describe("visual enrichment evidence taxonomy", () => {
    it("rejects placeholder source labels before evidence metadata reaches rendering", () => {
        assert.equal(isPlaceholderSourceLabel(legacyAiResearchSynthesisLabel), true);
        assert.equal(isPlaceholderSourceLabel("AI-synthesis"), true);
        assert.equal(isPlaceholderSourceLabel("Generated by AI"), true);
        assert.equal(sanitizeEvidenceSourceLabel(legacyAiSynthesisLabel), undefined);
        assert.equal(sanitizeEvidenceSourceLabel("OECD"), "OECD");
    });

    it("normalizes legacy source_url/source_label into schema version 2 evidence", () => {
        const enrichment = getVisualEnrichment({
            article_slug: "ai-adoption",
            enrichment: {
                schema_version: 1,
                visual_blocks: [chartBlock],
            },
        });

        assert.equal(enrichment.schema_version, 2);
        assert.equal(enrichment.visual_blocks[0].source_label, "Mckinsey");
        assert.equal(enrichment.evidence?.[0].article_slug, "ai-adoption");
        assert.equal(enrichment.evidence?.[0].visual_id, "chart_adoption");
        assert.equal(enrichment.evidence?.[0].evidence_type, "verified_statistic");
        assert.equal(enrichment.evidence?.[0].claim_type, "verified_statistic");
        assert.equal(enrichment.evidence?.[0].source_label, "Mckinsey");
        assert.equal(enrichment.evidence?.[0].badge_label, "Verified statistic");
        assert.match(enrichment.evidence?.[0].source_note ?? "", /Source-backed statistic/);
        assert.equal(enrichment.visual_blocks[0].evidence?.claim_id, "chart_adoption-evidence");
    });

    it("keeps explicit schema version 2 evidence while filling display helpers", () => {
        const enrichment = getVisualEnrichment({
            enrichment: {
                schema_version: 2,
                visual_blocks: [{ ...chartBlock, source_label: "OECD", source_url: "https://oecd.org/report" }],
                evidence: [{
                    claim_id: "claim-1",
                    visual_id: "chart_adoption",
                    claim_text: "Directional AI adoption claim.",
                    evidence_type: "time_sensitive_benchmark",
                    source_quality: "near_primary",
                    confidence: "high",
                    source_label: "OECD",
                    source_url: "https://oecd.org/report",
                }],
            },
        });

        assert.equal(enrichment.evidence?.[0].claim_id, "claim-1");
        assert.equal(enrichment.evidence?.[0].source_quality, "near_primary");
        assert.equal(enrichment.evidence?.[0].confidence, "high");
        assert.equal(enrichment.evidence?.[0].badge_label, "Time-sensitive benchmark");
        assert.match(enrichment.evidence?.[0].source_note ?? "", /Review before reuse/);
    });

    it("marks unsourced legacy visuals as unsupported with safe display labels", () => {
        const evidence = normalizeEvidenceForVisualBlock({ ...chartBlock, source_label: legacyAiSynthesisLabel, source_url: undefined });

        assert.equal(evidence.evidence_type, "unsupported");
        assert.equal(evidence.source_label, undefined);
        assert.equal(evidence.source_quality, "unknown");
        assert.equal(evidence.confidence, "low");
        assert.equal(evidence.badge_label, "Needs evidence");
    });

    it("generates stable badge labels and source notes from evidence type", () => {
        assert.equal(badgeLabelForEvidenceType("forecast"), "Forecast");
        assert.match(sourceNoteForEvidenceType("internal_estimate"), /directional/i);
    });

    it("infers source hierarchy quality for regulator, research, dataset, and vendor URLs", () => {
        assert.equal(normalizeEvidenceForVisualBlock({ ...chartBlock, source_url: "https://digital-strategy.ec.europa.eu/en/policies/example" }).source_quality, "primary");
        assert.equal(normalizeEvidenceForVisualBlock({ ...chartBlock, source_url: "https://www.mckinsey.com/capabilities/example" }).source_quality, "near_primary");
        assert.equal(normalizeEvidenceForVisualBlock({ ...chartBlock, source_url: "https://www.statista.com/statistics/example" }).source_quality, "secondary");
        assert.equal(normalizeEvidenceForVisualBlock({ ...chartBlock, source_url: "https://blog.hubspot.com/marketing/example" }).source_quality, "vendor");
    });
});

describe("relational diagram graph normalization", () => {
    it("normalizes node references and removes dangling or duplicate relationships", () => {
        const graph = normalizeBlogDiagramGraph(
            [
                { id: "Demand Signal", label: "Demand signal" },
                { id: "Delivery Capacity", label: "Delivery capacity" },
                { id: "Customer Trust", label: "Customer trust" },
            ],
            [
                { from: "Demand Signal", to: "Delivery Capacity", label: "increases", polarity: "positive", delay: true },
                { from: "Demand Signal", to: "Delivery Capacity", label: "duplicate", polarity: "positive" },
                { from: "Missing Node", to: "Customer Trust", label: "invalid", polarity: "negative" },
                { from: "Delivery Capacity", to: "Customer Trust", label: "improves", polarity: "positive" },
            ],
        );

        assert.deepEqual(graph.nodes.map((node) => node.id), [
            "demand-signal",
            "delivery-capacity",
            "customer-trust",
        ]);
        assert.deepEqual(graph.edges, [
            {
                from: "demand-signal",
                to: "delivery-capacity",
                label: "increases",
                polarity: "positive",
                delay: true,
            },
            {
                from: "delivery-capacity",
                to: "customer-trust",
                label: "improves",
                polarity: "positive",
                delay: undefined,
            },
        ]);
    });
});
