import "server-only";

import { generateImage, type ImageModel } from "ai";
import type { AiModelAlias } from "@/shared/lib/ai/models";
import { AiProviderError, normalizeAiProviderError } from "@/shared/lib/ai/errors";
import { getAiModel, getModelMetadata } from "@/shared/lib/ai/provider";
import { getVertexConfig, VERTEX_IMAGE_LOCATION } from "@/shared/lib/ai/vertex";

export interface VertexMediaPlaceholder {
    alias: Extract<AiModelAlias, "audio.tts" | "audio.transcribe" | "music.clip" | "music.pro" | "video.generate">;
    modelId: string;
    region: string;
    provider: "vertex";
}

export type VertexImageAlias = Extract<AiModelAlias, "image.fast" | "image.quality">;

export type VertexImageAspectRatio = "1:1" | "3:4" | "4:3" | "16:9" | "9:16";

export interface GenerateVertexImageInput {
    alias: VertexImageAlias;
    prompt: string;
    aspectRatio?: VertexImageAspectRatio;
    /** Appended to the prompt because Gemini image models do not accept Imagen's negativePrompt parameter. */
    negativePrompt?: string;
    seed?: number;
    abortSignal?: AbortSignal;
}

export interface VertexImage {
    base64: string;
    bytes: Uint8Array;
    mimeType: string;
    revisedPrompt?: string;
}

export interface VertexImageResult {
    alias: VertexImageAlias;
    modelId: string;
    provider: "vertex";
    region: string;
    images: VertexImage[];
}

interface VertexImageProviderMetadata {
    vertex?: {
        images?: Array<{ revisedPrompt?: unknown }>;
    };
}

function clampImageSeed(seed: number | undefined): number | undefined {
    if (seed === undefined) return undefined;
    if (!Number.isFinite(seed)) return undefined;
    return Math.min(2_147_483_647, Math.max(1, Math.floor(seed)));
}

/** Resolve metadata for media transports that remain route-owned. */
export function getVertexMediaPlaceholder(alias: VertexMediaPlaceholder["alias"]): VertexMediaPlaceholder {
    const metadata = getModelMetadata(alias, { provider: "vertex", allowFuture: true });
    return {
        alias,
        modelId: metadata.modelId,
        region: getVertexConfig().location,
        provider: "vertex",
    };
}

function buildGeminiImagePrompt(prompt: string, negativePrompt: string | undefined): string {
    const avoid = negativePrompt?.trim();
    return avoid ? `${prompt.trim()}\n\nAvoid these elements: ${avoid}.` : prompt.trim();
}

export async function generateVertexImage(input: GenerateVertexImageInput): Promise<VertexImageResult> {
    const metadata = getModelMetadata(input.alias, { provider: "vertex" });
    // Validate project credentials/config early while intentionally routing this
    // workload to the global location required by the GA Gemini image models.
    getVertexConfig();
    const seed = clampImageSeed(input.seed);

    try {
        const result = await generateImage({
            model: getAiModel(input.alias, { provider: "vertex" }) as ImageModel,
            prompt: buildGeminiImagePrompt(input.prompt, input.negativePrompt),
            // Gemini image endpoints support candidateCount=1. Multiple assets
            // are generated by separate calls at the route level.
            n: 1,
            aspectRatio: input.aspectRatio ?? "16:9",
            ...(seed !== undefined ? { seed } : {}),
            abortSignal: input.abortSignal,
        });

        const providerMetadata = result.providerMetadata as VertexImageProviderMetadata | undefined;
        const revisedPrompts = providerMetadata?.vertex?.images ?? [];
        const images = result.images.map((image, index) => ({
            base64: image.base64,
            bytes: image.uint8Array,
            mimeType: image.mediaType || "image/png",
            revisedPrompt: typeof revisedPrompts[index]?.revisedPrompt === "string"
                ? revisedPrompts[index].revisedPrompt
                : undefined,
        }));

        if (images.length === 0 || !images[0]?.base64) {
            throw new AiProviderError({
                code: "empty_output",
                message: "Vertex Gemini Image returned no image data.",
                provider: "vertex",
                modelAlias: input.alias,
                modelId: metadata.modelId,
                region: VERTEX_IMAGE_LOCATION,
                retryable: true,
            });
        }

        return {
            alias: input.alias,
            modelId: metadata.modelId,
            provider: "vertex",
            region: VERTEX_IMAGE_LOCATION,
            images,
        };
    } catch (error) {
        throw normalizeAiProviderError(error, {
            provider: "vertex",
            modelAlias: input.alias,
            modelId: metadata.modelId,
            region: VERTEX_IMAGE_LOCATION,
        });
    }
}
